/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three';
import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model({animationClip,isPaused, timeScale, props}) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/Alex_Rig_v2.4_rokoko_wface_aug30.glb');
  const { actions, mixer } = useAnimations(animations, group);

  function parseAnimationClip(json) {
    return THREE.AnimationClip.parse(json);
  } // parse to convert json to animation

  useEffect(() => {
    if (animationClip) {
      const parsedClip = parseAnimationClip(animationClip);
      const action =mixer.clipAction(parsedClip);  //combine mesh and animation
       if (parsedClip){
        // action.setEffectiveTimeScale(timeScale||1);
        if (isPaused){
          action.paused = true;
        } else {
          action.paused = false;
          action.play();
        }
       }
    }
  }, [animationClip,isPaused, timeScale, mixer]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="root">
          <group name="Alex_body">
            <skinnedMesh
              name="Alex_body_1"
              geometry={nodes.Alex_body_1.geometry}
              material={materials.Alex_body}
              skeleton={nodes.Alex_body_1.skeleton}
              morphTargetDictionary={nodes.Alex_body_1.morphTargetDictionary}
              morphTargetInfluences={nodes.Alex_body_1.morphTargetInfluences}
            />
            <skinnedMesh
              name="Alex_body_2"
              geometry={nodes.Alex_body_2.geometry}
              material={materials.Alex_nails}
              skeleton={nodes.Alex_body_2.skeleton}
              morphTargetDictionary={nodes.Alex_body_2.morphTargetDictionary}
              morphTargetInfluences={nodes.Alex_body_2.morphTargetInfluences}
            />
          </group>
          <skinnedMesh
            name="Alex_eyebrows"
            geometry={nodes.Alex_eyebrows.geometry}
            material={materials.Alex_hairs}
            skeleton={nodes.Alex_eyebrows.skeleton}
            morphTargetDictionary={nodes.Alex_eyebrows.morphTargetDictionary}
            morphTargetInfluences={nodes.Alex_eyebrows.morphTargetInfluences}
          />
          <group name="Alex_eyes">
            <skinnedMesh
              name="Alex_eyes_1"
              geometry={nodes.Alex_eyes_1.geometry}
              material={materials.Alex_eye_left}
              skeleton={nodes.Alex_eyes_1.skeleton}
            />
            <skinnedMesh
              name="Alex_eyes_2"
              geometry={nodes.Alex_eyes_2.geometry}
              material={materials.Alex_eye_right}
              skeleton={nodes.Alex_eyes_2.skeleton}
            />
            <skinnedMesh
              name="Alex_eyes_3"
              geometry={nodes.Alex_eyes_3.geometry}
              material={materials.Alex_cornea}
              skeleton={nodes.Alex_eyes_3.skeleton}
            />
          </group>
          <skinnedMesh
            name="Alex_fake_reflection"
            geometry={nodes.Alex_fake_reflection.geometry}
            material={materials.fake_reflection}
            skeleton={nodes.Alex_fake_reflection.skeleton}
            morphTargetDictionary={nodes.Alex_fake_reflection.morphTargetDictionary}
            morphTargetInfluences={nodes.Alex_fake_reflection.morphTargetInfluences}
          />
          <skinnedMesh
            name="Alex_Hair1"
            geometry={nodes.Alex_Hair1.geometry}
            material={materials.Alex_hairs}
            skeleton={nodes.Alex_Hair1.skeleton}
          />
          <group name="Alex_iris_left">
            <skinnedMesh
              name="Alex_iris_left_1"
              geometry={nodes.Alex_iris_left_1.geometry}
              material={materials.Alex_pupil}
              skeleton={nodes.Alex_iris_left_1.skeleton}
              morphTargetDictionary={nodes.Alex_iris_left_1.morphTargetDictionary}
              morphTargetInfluences={nodes.Alex_iris_left_1.morphTargetInfluences}
            />
            <skinnedMesh
              name="Alex_iris_left_2"
              geometry={nodes.Alex_iris_left_2.geometry}
              material={materials.Alex_iris}
              skeleton={nodes.Alex_iris_left_2.skeleton}
              morphTargetDictionary={nodes.Alex_iris_left_2.morphTargetDictionary}
              morphTargetInfluences={nodes.Alex_iris_left_2.morphTargetInfluences}
            />
          </group>
          <group name="Alex_iris_right">
            <skinnedMesh
              name="Alex_iris_right_1"
              geometry={nodes.Alex_iris_right_1.geometry}
              material={materials.Alex_pupil}
              skeleton={nodes.Alex_iris_right_1.skeleton}
              morphTargetDictionary={nodes.Alex_iris_right_1.morphTargetDictionary}
              morphTargetInfluences={nodes.Alex_iris_right_1.morphTargetInfluences}
            />
            <skinnedMesh
              name="Alex_iris_right_2"
              geometry={nodes.Alex_iris_right_2.geometry}
              material={materials.Alex_iris}
              skeleton={nodes.Alex_iris_right_2.skeleton}
              morphTargetDictionary={nodes.Alex_iris_right_2.morphTargetDictionary}
              morphTargetInfluences={nodes.Alex_iris_right_2.morphTargetInfluences}
            />
          </group>
          <skinnedMesh
            name="Alex_jeans"
            geometry={nodes.Alex_jeans.geometry}
            material={materials.Alex_jeans}
            skeleton={nodes.Alex_jeans.skeleton}
          />
          <group name="Alex_shoes">
            <skinnedMesh
              name="Alex_shoes_1"
              geometry={nodes.Alex_shoes_1.geometry}
              material={materials.Alex_shoes_white}
              skeleton={nodes.Alex_shoes_1.skeleton}
            />
            <skinnedMesh
              name="Alex_shoes_2"
              geometry={nodes.Alex_shoes_2.geometry}
              material={materials.Alex_shoes_red}
              skeleton={nodes.Alex_shoes_2.skeleton}
            />
            <skinnedMesh
              name="Alex_shoes_3"
              geometry={nodes.Alex_shoes_3.geometry}
              material={materials.Alex_laces}
              skeleton={nodes.Alex_shoes_3.skeleton}
            />
            <skinnedMesh
              name="Alex_shoes_4"
              geometry={nodes.Alex_shoes_4.geometry}
              material={materials.Alex_shoes_metalic}
              skeleton={nodes.Alex_shoes_4.skeleton}
            />
          </group>
          <group name="Alex_teeth_down">
            <skinnedMesh
              name="Alex_teeth_down_1"
              geometry={nodes.Alex_teeth_down_1.geometry}
              material={materials.Alex_teeth}
              skeleton={nodes.Alex_teeth_down_1.skeleton}
              morphTargetDictionary={nodes.Alex_teeth_down_1.morphTargetDictionary}
              morphTargetInfluences={nodes.Alex_teeth_down_1.morphTargetInfluences}
            />
            <skinnedMesh
              name="Alex_teeth_down_2"
              geometry={nodes.Alex_teeth_down_2.geometry}
              material={materials.Alex_gum}
              skeleton={nodes.Alex_teeth_down_2.skeleton}
              morphTargetDictionary={nodes.Alex_teeth_down_2.morphTargetDictionary}
              morphTargetInfluences={nodes.Alex_teeth_down_2.morphTargetInfluences}
            />
          </group>
          <group name="Alex_teeth_up">
            <skinnedMesh
              name="Alex_teeth_up_1"
              geometry={nodes.Alex_teeth_up_1.geometry}
              material={materials.Alex_teeth}
              skeleton={nodes.Alex_teeth_up_1.skeleton}
              morphTargetDictionary={nodes.Alex_teeth_up_1.morphTargetDictionary}
              morphTargetInfluences={nodes.Alex_teeth_up_1.morphTargetInfluences}
            />
            <skinnedMesh
              name="Alex_teeth_up_2"
              geometry={nodes.Alex_teeth_up_2.geometry}
              material={materials.Alex_gum}
              skeleton={nodes.Alex_teeth_up_2.skeleton}
              morphTargetDictionary={nodes.Alex_teeth_up_2.morphTargetDictionary}
              morphTargetInfluences={nodes.Alex_teeth_up_2.morphTargetInfluences}
            />
          </group>
          <skinnedMesh
            name="Alex_tongue"
            geometry={nodes.Alex_tongue.geometry}
            material={materials.Alex_tongue}
            skeleton={nodes.Alex_tongue.skeleton}
            morphTargetDictionary={nodes.Alex_tongue.morphTargetDictionary}
            morphTargetInfluences={nodes.Alex_tongue.morphTargetInfluences}
          />
          <skinnedMesh
            name="Alex_tshirt"
            geometry={nodes.Alex_tshirt.geometry}
            material={materials.Alex_tshirt}
            skeleton={nodes.Alex_tshirt.skeleton}
          />
          <primitive object={nodes.rootx} />
          <primitive object={nodes.c_eye_targetx} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/Alex_Rig_v2.4_rokoko_wface_aug30.glb');
